name: test
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '^1.20'
          - '^1.21'
          - '^1.22'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: vet
        run: go vet ./...
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.go == '^1.21' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ryomak/serrs